server:

  port: 8080
  max-http-request-header-size: 8KB
  jetty:
    max-http-form-post-size: 2MB

spring:

  application:
    name: panel
    version: 1.0.0


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  threads:
    virtual:
      enabled: true