server:

  port: 8080
  max-http-request-header-size: 8KB
  jetty:
    max-http-form-post-size: 2MB

spring:

  application:
    name: panel
    version: 1.0.0

  datasource:
    url: jdbc:mariadb://localhost:3306/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  threads:
    virtual:
      enabled: true


application:
  jwt-secret: "${JWT_SECRET:amazing-secret}"

  issuer: "transplant"